config/routes.rb
Rails.application.routes.draw do

  root to: 'items#index'
  get '/profile', to: 'user_profiles#show', as: 'profile'
  get '/profile/edit', to: 'user_profiles#edit', as: 'edit_profile'
  get "/carts/:cart_id/items/:item_id", to: "carts#add", as: :item_cart
  post "/carts/:cart_id/items/:item_id", to: "carts#change_quantity", as: :item_quantity
  delete "/carts/:cart_id/items/:item_id", to: "carts#destroy"

  resources :items
  get "payment", to: 'charges#new', as: :new_charge
  post "confirmation", to: 'charges#create', as: :charges

  get "my_cart", to: "carts#show", as: :cart_show
  resources :orders, only: [:create, :show]
  devise_for :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_lists
  has_many :items, through: :cart_lists
end

app/models/cart_list.rb
class CartList < ApplicationRecord
  belongs_to :cart
  belongs_to :item

  # validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :cart, presence: true
  validates :item, presence: true

end

app/models/item.rb
class Item < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :description, length: { in: 0..500 }
  validates :price, numericality: true
  validates :price, numericality: { greater_than: 0}
  
  has_many :cart_lists
  has_many :carts, through: :cart_lists

  has_many :order_lists
  has_many :orders, through: :order_lists

  has_one_attached :image

  def get_quantity(cart)
    list = self.cart_lists.find_by(cart: cart, item: self)
    return list.quantity
  end

  def set_quantity(cart, num)
    list = self.cart_lists.find_by(cart: cart, item: self)
    list.quantity = num
    list.save
  end

  def to_param
    title
  end

  def self.find(input)
    find_by_title(input)
  end


end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  has_many :order_lists
  has_many :items, through: :order_lists

end

app/models/order_list.rb
class OrderList < ApplicationRecord
  belongs_to :order
  belongs_to :item

  # validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :order, presence: true
  validates :item, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :cart, optional: true
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def filter_signed_in
    unless user_signed_in?
      flash[:danger] = "Merci de vous connecter pour accéder à cette page"
      redirect_to(root_path)
      return
    end
  end

  def filter_admin
    unless user_signed_in? && current_user.admin
      flash[:danger] = "Seuls les admin peuvent accéder à cette page"
      redirect_to(root_path)
      return
    end
  end 
  
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
    @current_user = User.all
  end


    # def current_user
    # return unless session[:user_id]
    # @current_user ||= User.find(session[:user_id])
  # end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :filter_signed_in
  before_action :get_cart_item

  def show
    @items = @cart.items
    @list = @cart.cart_lists.find_by(cart: @cart, item: @item)
  end

  def add
    # Cas où l'objet existe déjà dans le panier => on incrémente la quantité
    if @cart.items.include?(@item)
      @item.set_quantity(@cart, @item.get_quantity(@cart)+1)

    # S'il n'existe pas dans le panier
    else
      @cart.items << @item
      @item.set_quantity(@cart, 1)
    end

    redirect_back(fallback_location: root_path)
  end

  def destroy
    @cart.items.delete(@item)
    redirect_back(fallback_location: root_path)
  end

  def change_quantity
    quantity = params[:quantity].to_i
    if quantity <= 0
      quantity = 1
    end
    @item.set_quantity(@cart, quantity)
    redirect_to cart_show_path
  end

  private

  def get_cart_item
    @cart = current_user.cart
    if params[:item_id]
      @item = Item.find(params[:item_id])
    end
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :filter_signed_in

  def new
    @cart = current_user.cart
    get_total_price(@cart)
  end

  def create
    # cart & amount to pay
    @cart = current_user.cart
    @amount = (get_total_price(@cart)*100).to_i

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'eur'
    )

    #création d'un order une fois le paiement effectué
    @order = Order.create(user_id: current_user.id, total_price: @amount.to_f/100)
    @order.items << @cart.items

    # transfert des quantités vers les orders
    @order.items.each do |item|
      @order.order_lists.find_by(item: item).update(quantity: item.get_quantity(@cart))
      @cart.items.delete(item) #suppression de la cart_list
    end

    #envoi des emails une fois la commande créée
    ContactMailer.order_confirmation(@order).deliver_later
    ContactMailer.info_order('kasskq@gmail.com', @order).deliver_later
    ContactMailer.info_order('clemoun@yahoo.fr', @order).deliver_later

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  private

  def get_total_price(cart)
    @total_price = 0
    cart.items.each do |item|
      @total_price += item.price*item.get_quantity(cart)
    end
    return @total_price
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def new
    filter_admin
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to(@item)
    return
  end

  def edit
    filter_admin
    @item = Item.find(params[:id])
  end

  def update 
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to(@item)
    return
  end

  def index
    @items = Item.all.order("created_at asc")
    if user_signed_in?
      current_user.cart ||= Cart.create(user_id: current_user.id)
      current_user.save
    end
  end

  def show
    @item = Item.find(params[:id])

    @sug_items = []
    rand_array_cat = (Item.first.id..Item.last.id).to_a.shuffle
    4.times do |i|
      random_cat = Item.find_by_id(rand_array_cat[i])
      @sug_items << random_cat
    end 
  end

  private

  def item_params
    params.require(:item).permit(:title, :description, :price, :image)
  end

end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  def show
    @user = current_user
    @orders = @user.orders.order("id desc")
    @last_order = @user.orders.last
  end

  def edit
  end
end

app/helpers/alert_helper.rb
module AlertHelper
  def build_alert_classes(alert_type)
    classes = 'alert alert-dismissable '
    case alert_type.to_sym 
    when :alert, :danger, :error, :validation_errors
        classes += 'alert-danger'
    when :warning, :todo
        classes += 'alert-warning'
    when :notice, :success
        classes += 'alert-success'
    else 
        classes += 'alert-info'
    end
    return classes

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/cart/index.html.erb
  <h1>Mon Panier</h1>

app/views/carts/show.html.erb
<main>
    <header class="header-account-page bg-gradient-cart d-flex align-items-end" style="height: 250px">
        <div class="container">
            <div class="row">
                <div class=" col-lg-12">
                    <div class="row align-items-center mb-4">
                        <div class="col-md-5 mb-4 mb-md-0">
                            <span class="h2 mb-0 text-white d-block">Votre Panier.</span>
                            <span class="text-white">Résumé de vos achats sur notre site.</span>
                        </div>
                    </div>
                    <!-- Checkout navigation -->
                    <div class="d-flex">
                        <div class="btn-group btn-group-nav shadow" role="group" aria-label="Basic example">
                            <div class="btn-group" role="group">
                                <a href="#" class="btn btn-secondary btn-icon active">
                                    <span class="btn-inner--icon"><i class="fas fa-shopping-cart"></i></span>
                                    <span class="btn-inner--text d-none d-md-inline-block">Panier</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <% if @items.count > 0 %>


    <section class="slice slice-lg">
        <div class="container">
            <!-- Shopping cart -->
            <div class="table-responsive">
                <table class="table align-items-center">
                    <thead>
                        <tr>
                            <th>Produit</th>
                            <th>Prix</th>
                            <th>Quantité</th>
                            <th>Total</th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                      <%sum = 0%>
                      <%@items.each_with_index do |item,i|%>
                        <tr>
                          <td>
                            <div class="media align-items-center">
                              <%if item.image.attached?%>
                                <%= image_tag item.image.variant(resize: "80x90"), class: "mr-3" %>
                              <%end%>
                              <div class="media-body">
                                <div class="lh-100">
                                  <span class="text-dark font-weight-bold mb-0"><%=item.title%></span>
                                </div>
                              </div>
                            </div>
                          </td>
                          <td>
                            <span class="font-weight-bold"><%= sprintf('%.2f', item.price) %> €</span>
                          </td>
                          <td>
                            <form action=<%=item_quantity_url(@cart, item)%> method="post" style="display: flex;">
                              <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
                              <input type="number" name="quantity" class="form-control form-control-sm text-center" style="width: 80px;" value="<%=item.get_quantity(@cart)%>">
                              <button type="submit" name="commit" value="&#f01e" class="btn btn-primary" style="padding: 6px;"><i class="fas fa-redo"></i></button>
                              
                            </form>
                          </td>
                          <td>
                              <span class="font-weight-bold text-dark"><%= sprintf('%.2f', total_per_line = item.get_quantity(@cart)*item.price) %> €</span>
                          </td>
                          <td class="text-right">
                              <a href="<%= item_cart_path(@cart, item) %>" class="text-light" data-toggle="tooltip" data-original-title="Remove item" data-method="DELETE" data-confirm="Are you sure?" >
                                  <i class="fas fa-trash-alt"></i>
                              </a>
                          </td>
                        </tr>
                      <%sum += total_per_line%>
                      <%end%>
                    </tbody>
                </table>
            </div>
            <!-- Cart information -->
            <div class="mt-5 pt-5 delimiter-top">
                <div class="row justify-content-center">
                    <div class="col-md-5 col-lg-4 text-center">
                        <h5 class="mb-0">Total: <%=sum%> €</h5>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="slice bg-gradient-primary">
        <span class="tongue tongue-top">
    <i class="fas fa-angle-up"></i>
</span>
        <div class="container text-center">
            <h6 class="text-white">N'hésitez pas à retourner sur notre site pour acheter nos merveilleux chats</h6>
            <a href="<%= new_charge_path %>" class="btn btn-white btn-circle mt-4" method="POST">Validation avant paiement</a>
        </div>
    </section>

    <% else %>

    <section class="bg-darker">
            <div class="spotlight overflow-hidden bg-cover bg-size--cover" id="cart-empty" data-spotlight="fullscreen" data-separator-orientation="bottom">
                <span class="mask bg-gradient-dark opacity-5"></span>
                <div class="spotlight-holder">
                    <div class="container py-xl d-flex align-items-center">
                        <div class="col pt-md pt-lg-0">
                            <div class="row justify-content-center">
                                <div class="col-lg-8 text-center">
                                    <h6 class="font-weight-700 text-uppercase text-white ls-2 mb-md">Votre panier est vide !</h6>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
        </section>



    <section class="slice bg-gradient-primary">
        <span class="tongue tongue-top">
    <i class="fas fa-angle-up"></i>
</span>
        <div class="container text-center">
            <h6 class="text-white">Des images exclusives en HD, n'attendez plus !</h6>
            <a href="<%= root_path+'#sct-products' %>" class="btn btn-white btn-circle mt-4">Tous les chats</a>
        </div>
    </section>




    <% end %>

</main>

app/views/items/index.html.erb
<main>
    <section class="slice slice-lg bg-gradient-warning">
        <div class="position-absolute bottom-0 col-md-9 col-lg-9 col-xl-8 d-none d-md-block">
            <%= image_tag "catPNG.png", alt: "black cat land-page", class: "img-fluid" %>
        </div>
        <div class="container pt-lg">
            <div class="row justify-content-end">
                <div class="col-md-6 col-lg-5 text-center text-lg-left">
                    <div class="">
                        <h2 class="text-white my-4">
                            <span class="display-4 font-weight-light">Exclusif.</span>
                            <span class="d-block">Images inédites <strong>full HD.</strong></span>
                        </h2>
                        <p class="lead text-white">Simple et rapide. Près de 27 images de chats à découvrir. Photographes montpelliérains, chats 100% bios <a href="https://fr.wikipedia.org/wiki/In%C3%A9die">(nourris au prana)</a>.</p>
                        <div class="mt-5">
                            <a href="#sct-products" class="btn btn-white btn-circle btn-translate--hover btn-icon d-none d-xl-inline-block scroll-me">
                                <span class="btn-inner--text">Explorer</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row row-grid mt-lg d-none d-lg-flex">
                <div class="col-lg-4">
                    <div class="card shadow">
                        <div class="card-body">
                            <div class="d-flex align-items-start">
                                <div class="icon icon-shape icon-orange rounded-circle">
                                    <i class="fas fa-shipping-fast"></i>
                                </div>
                                <div class="icon-text px-4">
                                    <h5>Instantané</h5>
                                    <p class="mb-0">Envoi d'email automatique dès votre achat terminé avec les liens en HD</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="card shadow">
                        <div class="card-body">
                            <div class="d-flex align-items-start">
                                <div class="icon icon-shape icon-blue rounded-circle">
                                    <i class="fas fa-credit-card"></i>
                                </div>
                                <div class="icon-text px-4">
                                    <h5>Paiement sécurisé</h5>
                                    <p class="mb-0">Grâce à Stripe, vous disposez d'une interface de paiement sans risque</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="card shadow">
                        <div class="card-body">
                            <div class="d-flex align-items-start">
                                <div class="icon icon-shape icon-pink rounded-circle">
                                    <i class="fas fa-hand-holding-usd"></i>
                                </div>
                                <div class="icon-text px-4">
                                    <h5>Votre projet</h5>
                                    <p class="mb-0">Avec nos produits, nous vous garantissons un succès de carrière immédiat </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="shape-container" data-shape-style="wavify" data-shape-position="bottom">
            <svg width="100%" height="100%" version="1.1" xmlns="http://www.w3.org/2000/svg" class="shape-fill-white" data-toggle="wavify">
                <defs></defs>
                <path d="" class="shape-fill-white" />
            </svg>
        </div>
    </section>

    <section class="slice slice-lg" id="sct-products">
        <div class="container">
            <div class="mb-5 text-center">
                <h3 class="h6">Nos derniers produits</h3>
            </div>
            <div class="row">


                <%@items.each do |item|%>
                    <div class="col-lg-3 col-sm-6 col-sm-6 mb-5">
                        <div class="card card-product no-border shadow shadow--hover">
                            <div class="card-image">
                                <a href="<%= item_path(item) %>">
                                    <%if item.image.attached?%>
                                        <%= image_tag item.image.variant(resize: "210x145"), class: "img-center img-index"%>
                                    <%end%>
                                </a>
                                <span class="ribbon ribbon-right ribbon-primary rounded-circle">New</span>
                            </div>
                            <div class="card-body pt-0 text-center">
                                <a href="shop-product.html" class="card-title"><%=item.title%></a>
                                <span class="card-price"><%= sprintf('%.2f', item.price) %> €</span>
                                <%if user_signed_in?%>
                                <a href="<%= item_cart_path(current_user.cart, item)%> " class="btn btn-primary btn-sm btn-circle" id="button-index">Ajouter au panier</a><br>
                                <%if current_user.admin%>
                                    <a href="<%= edit_item_path(item) %>" class="btn btn-danger my-2 btn-sm btn-circle" style="padding: 2px; color: white;">Modifier l'objet</a><br>
                                <%end%>
                                <%end%> 
                                <a href="<%= item_path(item) %>">Détails</a>
                            </div>
                        </div>
                    </div>
                <%end%>
            </div>
        </div>

        <!-- ..................ALL PRODUCTS BUTTON................. -->
        <!-- <div class="text-center">
            <a href="shop-products.html" class="btn btn-sm btn-dark btn-circle">See all products</a>
        </div> -->

    </section>

    <section class="slice slice-lg bg-gradient-warning">
        <div class="position-absolute bottom-0 col-lg-6 col-xl-5 d-none d-lg-block">
            <%= image_tag "catPNG.png", alt: "black cat", class: "img-fluid", style: "height: 600px;" %>
        </div>
        <div class="container">
            <div class="row justify-content-end">
                <div class="col-lg-6 col-xl-7 text-center text-lg-right">
                    <div class="mb-5">
                        <h1 class="text-white">Alors, y sont pas mignons ??</h1>
                        <p class="lead text-white mt-2">Pour profiter pleinement des services, <a href="<%= new_user_session_path %>"><strong>connectez vous</strong></a> ou <a href="<%= new_user_registration_path %>"><strong>devenez membre </strong></a>.</p>
                    </div>
                </div>
            </div>
            <br>
        </div>
        <%= image_tag("img/backgrounds/" + "clouds-bottom.png", alt: "clouds", style: "margin-bottom: -110px; width: 100%") %>
    </section>
</main>

app/views/items/show.html.erb
<br><br><br>
<section class="slice slice-lg" id="sct-products">
    <div class="container">
        <div class="row">

            <div class="col-lg-6">

                <!-- Product gallery -->
                <div class="mb-5">
                    <a href="">
                        <%if @item.image.attached?%>
                            <%= image_tag @item.image.variant(resize: "550x400"), class: "img-fluid rounded shadow shadow-lg--hover"%>
                        <%end%>
                    </a>
                </div>
            </div>
            <div class="col-lg-6">
                <form class="pl-lg-4">

                    <!-- Product title -->
                    <h1>Hey, je m'appelle 
                        <%=@item.title%> !</h1>

                    <!-- Product description -->
                    <div class="mt-4">
                        <small class="text-dark font-weight-bold d-block mb-2">Description:</small>
                        <p class="text-sm lh-150">
                            <%=@item.description%>
                        </p>
                    </div>


                    <!-- Rating stars -->
                    <p style="width: 170px"> Cute
                        <span class="static-rating static-rating-sm" style="float: right;">
                            <i class="star fas fa-star voted"></i>
                            <i class="star fas fa-star voted"></i>
                            <i class="star fas fa-star voted"></i>
                            <% if rand(0..2) == 0 %>
                            <i class="star fas fa-star voted"></i>
                            <i class="star fas fa-star voted"></i>
                            <% elsif rand(0..1) == 0%>
                            <i class="star fas fa-star voted"></i>
                            <i class="star fas fa-star"></i>
                            <% else %>
                            <i class="star fas fa-star"></i>
                            <i class="star fas fa-star"></i>
                            <% end %>

                        </span>
                    </p>
                    <p style="width: 170px"> Crazy
                        <span class="static-rating static-rating-sm" style="float: right;">
                            <i class="star fas fa-star voted"></i>
                            <i class="star fas fa-star voted"></i>
                            <i class="star fas fa-star voted"></i>
                            <i class="star fas fa-star"></i>
                            <i class="star fas fa-star"></i>
                        </span>
                    </p>

                    <!-- Quantity -->
                    <div class="mt-4">
                        <br>
                        <div class="d-flex">
                            <h3 class="d-block font-weight-bold text-dark mb-2" style="margin-top: 10px; margin-right: 10px;">
                                <%=@item.price%> €</h3>
                            <%if user_signed_in?%>
                            <%= link_to "Ajout au panier", item_cart_path(current_user.cart, @item), class: "btn btn-primary ml-3"%> <br>
                            <%= link_to "Lui acheter à manger", "https://fish-store.herokuapp.com/", class: "btn btn-light ml-3"%>
                            <%end%>
                        </div>
                    </div>

                    <!-- Product info -->
                </form>
            </div>
        </div>
        <div>
            <small class="d-block font-weight-bold text-dark">Entretien</small>
            <ul class="list-unstyled list-icon">
                <li class="text-sm py-1">
                    <i class="fas fa-tshirt mr-3"></i>Fourrure 100% naturelle, qualité garantie depuis 1875
                </li>
                <li class="text-sm py-1">
                    <i class="fas fa-air-freshener mr-3"></i>Lavable en machine à 30&deg;/40&deg;C (nan mais en vrai, lave pas ton chat mec !)
                </li>
                <li class="text-sm py-1">
                    <i class="fas fa-charging-station mr-3"></i>Teméprature de repassage conseillée : entre 110&deg;C/230&deg;C
                </li>
            </ul>
        </div>
    </div>
</section>



<section>
    <div class="container">
        <div class="mb-md text-center">
            <h5>Suggestion de produits</h5>
            <div class="fluid-paragraph text-center mt-2">
                <p class="lead lh-180">N'attendez plus pour découvrir nos images exceptionnelles !</p>
            </div>
        </div>


        <div class="row">

            <% @sug_items.each do |item|%>
            <div class="col-lg-3 col-sm-6 col-sm-6 mb-5">
                <div class="card card-product no-border shadow shadow--hover">
                    <div class="card-image">
                        <a href="<%= item_path(item) %>">
                            <%if item.image.attached?%>
                                <%= image_tag item.image.variant(resize: "210x145"), class: "img-center img-index"%>
                            <%end%>

                            </a>

                        <span class="ribbon ribbon-right ribbon-primary rounded-circle">New</span>

                    </div>

                    <div class="card-body pt-0 text-center">
                        <a href="<%= item_path(item) %>" class="card-title">
                            <%=item.title%></a>
                        <span class="card-price">
                            <%=item.price%> €</span>
                        <%= link_to "détails", item_path(item)%>
                    </div>
                </div>
            </div>
            <%end%>
        <%= image_tag("img/backgrounds/" + "clouds-bottom.png", alt: "clouds", style: "margin-bottom: -110px") %>

        </section>
        <br><br><br>

app/views/layouts/_footer.html.erb
<footer>
        <div class="container" >
            <div class="row pt-md">
                <a href="<%= root_path %>" style="height: 100px; margin-top: 20px">
                    <%= image_tag "cat-logo-dark.png", :alt => "cat-logo", style: "height: 90px;" -%>
                </a>
                <div class="col-lg-2" style="padding-top: 40px; margin-left: 150px; margin-right: 50px">
                    <h6 class="heading mb-3">Profil</h6>
                    <ul class="list-unstyled">
                        <li><a href="<%= profile_path %>">Ma page</a></li>
                    </ul>
                </div>
                <div class="col-lg-2" style="padding-top: 40px; margin-right: 90px">
                    <h6 class="heading mb-3">Paramètres</h6>
                    <ul class="list-unstyled">
                        <li><a href="<%= edit_user_registration_path %>">Éditer mon profil</a></li>
                    </ul>
                </div>
                <div class="col-lg-2" style="padding-top: 40px">
                    <h6 class="heading mb-3">Mon panier</h6>
                    <ul class="list-unstyled">
                        <li><a href="<%= cart_show_path %>">Mes commandes</a></li>
                    </ul>
                </div>
            </div>
            <div class="row align-items-center justify-content-md-between py-4 mt-4 delimiter-top">
                <div class="col-md-6">
                    <div class="copyright text-sm font-weight-bold text-center text-md-left">
                        <strong>THP Team MONTPELLIER</strong>  &copy; 2018 <a href="https://webpixels.io/" class="font-weight-bold" target="_blank">Webpixels</a>. All rights reserved.
                    </div>
                </div>
                <div class="col-md-6">
                    <ul class="nav justify-content-center justify-content-md-end mt-3 mt-md-0">
                        <li class="nav-item">
                            <a class="nav-link" href="https://dribbble.com/webpixels" target="_blank">
                                <i class="fab fa-dribbble"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="https://instagram.com/webpixelsofficial" target="_blank">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="https://github.com/webpixels" target="_blank">
                                <i class="fab fa-github"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="https://facebook.com/webpixels" target="_blank">
                                <i class="fab fa-facebook"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>